spring:
  application:
    name: libraryapi
  profiles:
    active: production
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: update
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{36}){cyan} %clr(:%line){faint} - %msg%n"
  file:
    name: app.log
  level:
    root: warn
    com:
      example:
        librayapi: trace
    org:
      springframework:
        web: debug
        security: trace

# trace
# debug
# info
# warn
# error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  override-with-generic-response: false

# production
---
spring:
  config:
    activate:
      on-profile: production
    jpa:
      show-sql: false

# homologacao
---
spring:
  config:
    activate:
      on-profile: production
    jpa:
      show-sql: false
    datasource:
      url: jdbc:postgresql://localhost:5432/library