spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: update
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 8134547136-0il8l1u3flb6phkqdb42qb4pmscmr4u4.apps.googleusercontent.com
            client-secret: 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