spring:
  application:
    name: login-auth-api

  datasource:
    url:  jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${jwt.public.key}

jwt:
  public:
    key: "classpath:app.pub"
  private:
    key: "classpath:app.key"